# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import QThread, pyqtSignal,QObject
from PyQt5.QtGui import QTextCursor, QPalette, QColor, QFont, QIcon, QPixmap
import sys  # 导入sys模块
import logging
import os
from pathlib import Path


# ------------------------------
# 日志处理（优化滚动条样式）
# ------------------------------
class QTextEditLogger(logging.Handler):
    def __init__(self, text_edit):
        super().__init__()
        self.text_edit = text_edit
        self.text_edit.setReadOnly(True)
        self.formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
        # 日志框样式：调整圆角为4px，添加滚动条样式
        self.text_edit.setStyleSheet("""
            QTextEdit {
                background-color: #f8f9fa;
                border: 1px solid #dee2e6;
                border-radius: 4px; /* 圆角缩小 */
                padding: 10px;
                font-family: "Microsoft YaHei", Arial, sans-serif;
                font-size: 13px;
                color: #212529;
            }
            /* 滚动条样式 */
            QScrollBar:vertical {
                border: none;
                background: #f1f1f1;
                width: 8px;
                border-radius: 4px;
            }
            QScrollBar::handle:vertical {
                background: #c1c1c1;
                border-radius: 4px;
                min-height: 20px;
            }
            QScrollBar::handle:vertical:hover {
                background: #a8a8a8;
            }
            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {
                border: none;
                background: none;
            }
            QScrollBar:horizontal {
                border: none;
                background: #f1f1f1;
                height: 8px;
                border-radius: 4px;
            }
            QScrollBar::handle:horizontal {
                background: #c1c1c1;
                border-radius: 4px;
                min-width: 20px;
            }
            QScrollBar::handle:horizontal:hover {
                background: #a8a8a8;
            }
            QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {
                border: none;
                background: none;
            }
        """)

    def emit(self, record):
        msg = self.format(record)
        self.text_edit.moveCursor(QTextCursor.MoveOperation.End)
        self.text_edit.insertPlainText(msg + '\n')
        self.text_edit.moveCursor(QTextCursor.MoveOperation.End)



class Ui_MainWindow(QMainWindow):
    def __init__(self, parent=None):
        super(Ui_MainWindow, self).__init__(parent)
        self.selected_env = "pre"
        # ------------------------------
        # 关键：获取程序实际安装目录（兼容开发/打包环境）
        # ------------------------------
        if getattr(sys, 'frozen', False):
            # 打包后的 exe 环境：sys.frozen 为 True，_MEIPASS 是临时解压目录（单文件模式）
            # 但我们需要 exe 本身所在的目录，而非临时目录
            self.app_path = os.path.dirname(sys.executable)  # 获取 exe 所在目录
        else:
            # 开发环境：获取当前脚本所在目录
            self.app_path = os.path.dirname(os.path.abspath(__file__))

        # 转换为 Path 对象（可选，方便路径拼接）
        self.app_path = Path(self.app_path)

        self.key_files = []
        self.selected_folder = ""
        self.encrypt_thread = None
        self.pubkey_path = ""

        self.setupUi(self)  # 初始化窗体设置
        self.set_style()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(922, 662)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setObjectName("radioButton")
        self.radioButton.setChecked(True)
        self.radioButton.toggled.connect(lambda checked: self.set_env("pre") if checked else None)

        self.horizontalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_2.toggled.connect(lambda checked: self.set_env("formal") if checked else None)

        self.horizontalLayout_2.addWidget(self.radioButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit.setObjectName("textEdit")

        self.verticalLayout_3.addWidget(self.textEdit)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 922, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.setup_logger()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def set_style(self):
        """统一设置组件样式（修复圆角和标题）"""
        font = QFont("Microsoft YaHei", 11)
        self.setFont(font)

        # GroupBox 样式：修复标题显示，圆角调整为4px
        group_box_style = """
            QGroupBox {
                font-size: 12px;
                font-weight: bold;
                color: #212529;
                border: 1px solid #dee2e6;
                border-radius: 4px; /* 圆角缩小 */
                background-color: #fafafa;
                margin-top: 12px; /* 增加顶部边距，避免标题被截断 */
            }margin-top: 18px; /* 增大顶部边距，给标题更多空间 */
            QGroupBox::title {
                subcontrol-origin: margin;
                left: 15px;
                top: -4px; /* 调整标题位置，避免被截断 */
                background-color: #fafafa;
                padding: 0 8px;
                height: 16px; /* 明确标题高度，确保显示完整 */
                margin-top: 8px; /* 增大顶部边距，给标题更多空间 */
            }
        """
        for widget in self.findChildren(QGroupBox):
            widget.setStyleSheet(group_box_style)

        # 按钮样式：圆角调整为4px
        button_style = """
            QPushButton {
                background-color: #2196f3;
                color: white;
                border: none;
                border-radius: 4px; /* 圆角缩小 */
                padding: 8px 16px;
                font-size: 11px;
                font-weight: 500;
                cursor: pointer;
            }
            QPushButton:hover {
                background-color: #1976d2;
            }
            QPushButton:disabled {
                background-color: #bbdefb;
                cursor: not-allowed;
            }
            QPushButton#clear_log_btn {
                background-color: #6c757d;
            }
            QPushButton#clear_log_btn:hover {
                background-color: #5a6268;
            }
        """
        self.pushButton.setStyleSheet(button_style)
        self.pushButton_2.setStyleSheet(button_style)
        self.pushButton_3.setStyleSheet(button_style.replace("QPushButton {", "QPushButton#clear_log_btn {"))
        self.pushButton_3.setObjectName("clear_log_btn")

        # 输入框样式：圆角调整为4px
        line_edit_style = """
            QLineEdit {
                border: 1px solid #dee2e6;
                border-radius: 4px; /* 圆角缩小 */
                padding: 8px 12px;
                font-size: 11px;
                background-color: white;
            }
            QLineEdit:read-only {
                background-color: #f8f9fa;
                color: #495057;
            }
        """
        self.lineEdit.setStyleSheet(line_edit_style)
        self.lineEdit_2.setStyleSheet(line_edit_style)

        # 单选框样式（无修改）
        radio_style = """
            QRadioButton {
                font-size: 11px;
                color: #212529;
                margin-right: 20px;
            }
            QRadioButton::indicator {
                width: 16px;
                height: 16px;
                border-radius: 8px;
                border: 2px solid #adb5bd;
            }
            QRadioButton::indicator:checked {
                background-color: #2196f3;
                border-color: #2196f3;
            }
        """
        self.radioButton.setStyleSheet(radio_style)
        self.radioButton_2.setStyleSheet(radio_style)

        # 标签样式（无修改）
        label_style = """
            QLabel {
                font-size: 11px;
                color: #212529;
            }
        """
        for widget in self.findChildren(QLabel):
            widget.setStyleSheet(label_style)

    def update_pubkey_path(self):
        """公钥路径样式调整（圆角同步为4px）"""
        if self.selected_env == "pre":
            # 拼接：exe目录 → public_key → pre_env → publickey.pem
            pubkey_path = self.app_path / "public_key" / "pre_env" / "publickey.pem"
        else:
            pubkey_path = self.app_path / "public_key" / "formal_env" / "publickey.pem"

        self.pubkey_path = str(pubkey_path)
        self.lineEdit_2.setText(self.pubkey_path)
        if not os.path.exists(pubkey_path):
            self.lineEdit_2.setStyleSheet("""
                        QLineEdit {
                            border: 1px solid #dc3545;
                            border-radius: 4px; /* 圆角缩小 */
                            padding: 8px 12px;
                            font-size: 11px;
                            background-color: #fff8f8;
                            color: #dc3545;
                        }
                    """)
            logging.warning(
                f"当前{'' if self.selected_env == 'pre' else '生产'}环境公钥文件不存在：{pubkey_path}\n"
                f"请检查是否已在对应目录放置 publickey.pem 文件"
            )
        else:
            self.lineEdit_2.setStyleSheet("""
                        QLineEdit {
                            border: 1px solid #dee2e6;
                            border-radius: 4px; /* 圆角缩小 */
                            padding: 8px 12px;
                            font-size: 11px;
                            background-color: #f8f9fa;
                            color: #495057;
                        }
                    """)
            logging.info(f"当前公钥文件：{pubkey_path}（校验通过）")

    def set_env(self, env_type: str):
        self.selected_env = env_type
        env_name = "预生产" if env_type == "pre" else "生产"
        logging.info(f"已切换至{env_name}环境")
        self.update_pubkey_path()

    def select_folder(self):
        folder = QFileDialog.getExistingDirectory(self, "选择文件夹路径")
        if folder:
            self.selected_folder = folder
            self.lineEdit.setText(folder)
            self.key_files = [
                os.path.join(root, file)
                for root, dirs, files in os.walk(folder)
                for file in files
                # if file.lower().endswith(".key")
            ]
        return self.key_files

    def setup_logger(self):
        logger = logging.getLogger()
        logger.setLevel(logging.INFO)
        logger.handlers.clear()

        qt_handler = QTextEditLogger(self.textEdit)
        logger.addHandler(qt_handler)

        console_handler = logging.StreamHandler()
        console_handler.setFormatter(logging.Formatter('%(asctime)s - %(levelname)s - %(message)s'))
        logger.addHandler(console_handler)

    def clear_log(self):
        self.textEdit.clear()
        logging.info("日志已清空")

    def update_log(self, msg: str):
        logger = logging.getLogger()
        if msg.startswith("ERROR - "):
            error_msg = msg.replace("ERROR - ", "")
            logger.error(error_msg)
        else:
            logger.info(msg)

    def start_encrypt(self):
        if not self.selected_folder:
            logging.warning("加密操作取消：未选择待加密文件所在文件夹！")
            return

        if not os.path.exists(self.pubkey_path):
            logging.error(f"加密操作取消：当前环境公钥文件不存在：{self.pubkey_path}（请检查文件后重试）")
            return

        if not self.key_files:
            logging.warning("加密操作取消：未找到可加密的 .key 文件！")
            return

        selected_item = self.key_list.currentItem()
        if not selected_item or "未找到" in selected_item.text():
            logging.warning("加密操作取消：未选择要加密的 .key 文件！")
            return

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "原始证书导入"))
        self.label.setText(_translate("MainWindow", "原始证书位置:"))
        self.pushButton.setText(_translate("MainWindow", "选择文件夹路径"))
        self.groupBox_2.setTitle(_translate("MainWindow", "环境配置"))
        self.label_2.setText(_translate("MainWindow", "运行环境:"))
        self.radioButton.setText(_translate("MainWindow", "预生产环境"))
        self.radioButton_2.setText(_translate("MainWindow", "生产环境"))
        self.label_3.setText(_translate("MainWindow", "公钥选择:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "罐装文件夹制作日志"))
        self.pushButton_2.setText(_translate("MainWindow", "开始制作罐装文件"))
        self.pushButton_3.setText(_translate("MainWindow", "清空日志"))


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle("Fusion")
    palette = QPalette()
    palette.setColor(QPalette.ColorRole.Window, QColor(248, 249, 250))
    palette.setColor(QPalette.ColorRole.WindowText, QColor(33, 37, 41))
    app.setPalette(palette)

    MainWindow = QtWidgets.QMainWindow()  # 创建窗体对象
    ui = Ui_MainWindow()  # 创建PyQt5设计的窗体对象
    ui.setupUi(MainWindow)  # 调用PyQt5窗体的方法对窗体对象进行初始化设置
    MainWindow.show()  # 显示窗体
    sys.exit(app.exec_())  # 程序关闭时退出进程