# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import QThread, pyqtSignal,QObject
from PyQt5.QtGui import QTextCursor, QPalette, QColor, QFont, QIcon, QPixmap
import sys  # 导入sys模块

class Ui_MainWindow(QMainWindow):
    def __init__(self, parent=None):
        super(Ui_MainWindow, self).__init__(parent)
        self.selected_env = "pre"
        self.setupUi(self)  # 初始化窗体设置
        self.set_style()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(922, 662)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_2.addWidget(self.radioButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_3.addWidget(self.textEdit)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_4.addWidget(self.pushButton_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 922, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def set_style(self):
        """统一设置组件样式（修复圆角和标题）"""
        font = QFont("Microsoft YaHei", 11)
        self.setFont(font)

        # GroupBox 样式：修复标题显示，圆角调整为4px
        group_box_style = """
            QGroupBox {
                font-size: 12px;
                font-weight: bold;
                color: #212529;
                border: 1px solid #dee2e6;
                border-radius: 4px; /* 圆角缩小 */
                background-color: #fafafa;
                margin-top: 12px; /* 增加顶部边距，避免标题被截断 */
            }margin-top: 18px; /* 增大顶部边距，给标题更多空间 */
            QGroupBox::title {
                subcontrol-origin: margin;
                left: 15px;
                top: -4px; /* 调整标题位置，避免被截断 */
                background-color: #fafafa;
                padding: 0 8px;
                height: 16px; /* 明确标题高度，确保显示完整 */
                margin-top: 8px; /* 增大顶部边距，给标题更多空间 */
            }
        """
        for widget in self.findChildren(QGroupBox):
            widget.setStyleSheet(group_box_style)

        # 按钮样式：圆角调整为4px
        button_style = """
            QPushButton {
                background-color: #2196f3;
                color: white;
                border: none;
                border-radius: 4px; /* 圆角缩小 */
                padding: 8px 16px;
                font-size: 11px;
                font-weight: 500;
                cursor: pointer;
            }
            QPushButton:hover {
                background-color: #1976d2;
            }
            QPushButton:disabled {
                background-color: #bbdefb;
                cursor: not-allowed;
            }
            QPushButton#clear_log_btn {
                background-color: #6c757d;
            }
            QPushButton#clear_log_btn:hover {
                background-color: #5a6268;
            }
        """
        self.pushButton.setStyleSheet(button_style)
        self.pushButton_2.setStyleSheet(button_style)
        self.pushButton_3.setStyleSheet(button_style.replace("QPushButton {", "QPushButton#clear_log_btn {"))
        self.pushButton_3.setObjectName("clear_log_btn")

        # 输入框样式：圆角调整为4px
        line_edit_style = """
            QLineEdit {
                border: 1px solid #dee2e6;
                border-radius: 4px; /* 圆角缩小 */
                padding: 8px 12px;
                font-size: 11px;
                background-color: white;
            }
            QLineEdit:read-only {
                background-color: #f8f9fa;
                color: #495057;
            }
        """
        self.lineEdit.setStyleSheet(line_edit_style)
        self.lineEdit_2.setStyleSheet(line_edit_style)

        # 单选框样式（无修改）
        radio_style = """
            QRadioButton {
                font-size: 11px;
                color: #212529;
                margin-right: 20px;
            }
            QRadioButton::indicator {
                width: 16px;
                height: 16px;
                border-radius: 8px;
                border: 2px solid #adb5bd;
            }
            QRadioButton::indicator:checked {
                background-color: #2196f3;
                border-color: #2196f3;
            }
        """
        self.radioButton.setStyleSheet(radio_style)
        self.radioButton_2.setStyleSheet(radio_style)

        # 标签样式（无修改）
        label_style = """
            QLabel {
                font-size: 11px;
                color: #212529;
            }
        """
        for widget in self.findChildren(QLabel):
            widget.setStyleSheet(label_style)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "原始证书导入"))
        self.label.setText(_translate("MainWindow", "原始证书位置:"))
        self.pushButton.setText(_translate("MainWindow", "选择文件夹路径"))
        self.groupBox_2.setTitle(_translate("MainWindow", "环境配置"))
        self.label_2.setText(_translate("MainWindow", "运行环境:"))
        self.radioButton.setText(_translate("MainWindow", "预生产环境"))
        self.radioButton_2.setText(_translate("MainWindow", "生产环境"))
        self.label_3.setText(_translate("MainWindow", "公钥选择:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "罐装文件夹制作日志"))
        self.pushButton_2.setText(_translate("MainWindow", "开始制作罐装文件"))
        self.pushButton_3.setText(_translate("MainWindow", "清空日志"))


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle("Fusion")
    palette = QPalette()
    palette.setColor(QPalette.ColorRole.Window, QColor(248, 249, 250))
    palette.setColor(QPalette.ColorRole.WindowText, QColor(33, 37, 41))
    app.setPalette(palette)

    MainWindow = QtWidgets.QMainWindow()  # 创建窗体对象
    ui = Ui_MainWindow()  # 创建PyQt5设计的窗体对象
    ui.setupUi(MainWindow)  # 调用PyQt5窗体的方法对窗体对象进行初始化设置
    MainWindow.show()  # 显示窗体
    sys.exit(app.exec_())  # 程序关闭时退出进程